version: "3.9"

services:
  server:
    build: ./server
    container_name: movie_server
    env_file:
      - ./server/.env
    ports:
      - "5000:4001"   # Host 4001 â†’ Container 4001 (your Node.js server)
    restart: unless-stopped
    networks:
      - movie_network

  client:
    build: ./client
    container_name: movie_client
    env_file:
      - ./client/.env
    ports:
      - "3000:3000"
    depends_on:
      - server
    restart: unless-stopped
    networks:
      - movie_network

networks:
  movie_network:
    driver: bridge
